#!/usr/bin/env python3
"""Generate the minimal kbuild artifacts needed to compile a tiny kernel
module against linux-5.15.134 headers WITHOUT running `make modules_prepare`.

Outputs under <ksrc>/:
  include/generated/autoconf.h      from analysis/kernel_ev/kernel.config
  include/generated/bounds.h        dummy-correct values (harmless for our use)
  include/generated/utsrelease.h    UTS_RELEASE = "5.15.134"
  include/config/auto.conf          (same content as autoconf.h, for kconfig.h)
  arch/arm64/include/generated/asm/*  copies of asm-generic where included
Usage: python gen_kernel_inc.py <ksrc>
"""
import os, re, sys, shutil

ksrc = sys.argv[1]
cfg_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "analysis", "kernel_ev", "kernel.config")

defines = []
for line in open(cfg_path, encoding="utf-8", errors="replace"):
    line = line.rstrip("\n")
    m = re.match(r"^CONFIG_([A-Za-z0-9_]+)=(.*)$", line)
    if not m:
        continue
    name, val = m.group(1), m.group(2)
    if val == "y":
        defines.append(f"#define CONFIG_{name} 1")
    elif val == "m":
        defines.append(f"#define CONFIG_{name}_MODULE 1")
    elif val.startswith('"'):
        defines.append(f"#define CONFIG_{name} {val}")
    else:
        defines.append(f"#define CONFIG_{name} {val}")

gen = os.path.join(ksrc, "include", "generated")
os.makedirs(gen, exist_ok=True)
with open(os.path.join(gen, "autoconf.h"), "w") as f:
    f.write("\n".join(defines) + "\n")
with open(os.path.join(gen, "utsrelease.h"), "w") as f:
    f.write('#define UTS_RELEASE "5.15.134"\n')
with open(os.path.join(gen, "bounds.h"), "w") as f:
    f.write("#define NR_PAGEFLAGS 20\n#define MAX_NR_ZONES 4\n"
            "#define SPINLOCK_SIZE 4\n#define L1_CACHE_BYTES 64\n")

# arch/arm64/include/generated: needed wrappers
agen = os.path.join(ksrc, "arch", "arm64", "include", "generated", "asm")
os.makedirs(agen, exist_ok=True)
generic = os.path.join(ksrc, "include", "asm-generic")
need = ["checksum.h" not in "x", ]  # placeholder, filled below
wrappers = ["early_ioremap.h", "local64.h", "mcs_spinlock.h", "qspinlock.h",
            "qrwlock.h", "segment.h", "trace_clock.h", "vtime.h",
            "current.h", "kprobes.h", "mm-arch-hooks.h", "word-at-a-time.h",
            "compat.h", "device.h", "div64.h", "dma-mapping.h", "emergency-restart.h",
            "exec.h", "extable.h", "fb.h", "futex.h", "hardirq.h", "hw_irq.h",
            "irq.h", "irq_regs.h", "irq_work.h", "kdebug.h", "kmap_types.h",
            "local.h", "msi.h", "parport.h", "pci_iomap.h", "percpu.h",
            "preempt.h", "rwonce.h", "serial.h", "set_memory.h", "switch_to.h",
            "timex.h", "topology.h", "trace_clock.h", "unaligned.h",
            "user.h", "vga.h", "xor.h", "xor_32.h"]
for w in wrappers:
    src = os.path.join(generic, os.path.basename(w))
    dst = os.path.join(agen, os.path.basename(w))
    if os.path.exists(src) and not os.path.exists(dst):
        with open(dst, "w") as f:
            f.write(f"#include <asm-generic/{os.path.basename(w)}>\n")

# asm-offsets.h (generated normally by Kbuild; our module path does not need
# real offsets, but include/linux/*.h includes it unconditionally in some trees)
with open(os.path.join(agen, "asm-offsets.h"), "w") as f:
    f.write("/* generated by gen_kernel_inc.py (dummies) */\n")

print("generated:", gen, "and arch wrappers")
