worker_processes 1;
error_log /tmp/nginx_web.err;
pid /tmp/nginx_web.pid;
events { worker_connections 64; }
http {
    include /fhrom/fhconf/webconf/mime.types;
    default_type application/octet-stream;
    access_log off;
    server {
        listen 192.168.9.1:8080;
        server_name localhost;
        set $login_user 0;
        root /www/html;
        index login.html;
        location = /fh_app/api {
            include /fhrom/fhconf/webconf/fastcgi.conf;
            fastcgi_pass 127.0.0.1:8840;
            limit_except POST { deny all; }
        }
        location ~ ^/(api/tmp/FHNCAPIS|api/tmp/FHTOOLAPIS)$ {
            include /fhrom/fhconf/webconf/fastcgi.conf;
            fastcgi_param REDIRECT_FROM_NGINX "true";
            fastcgi_param METHOD_FROM_NGINX "web_do_cpe_manage";
            fastcgi_pass 127.0.0.1:8840;
        }
        location ^~ /fh_api/sign/ {
            include /fhrom/fhconf/webconf/fastcgi.conf;
            fastcgi_pass 127.0.0.1:8840;
        }
        location ^~ /fh_api/tmp/ {
            include /fhrom/fhconf/webconf/fastcgi.conf;
            fastcgi_pass 127.0.0.1:8840;
        }
        location ^~ /fh_api/long/ {
            include /fhrom/fhconf/webconf/fastcgi.conf;
            fastcgi_pass 127.0.0.1:8840;
        }
        location / { try_files $uri $uri/ /login.html; }
    }
}
